### ISSUE TITLE
Súper Selectos

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#100]
Merchant name: Súper Selectos
Address: PQ42+P8C, San Salvador, El Salvador
Lat: 13.706848183442922
Long: -89.24942732255329
OSM: https://www.openstreetmap.org/edit#map=19/13.706848183442922/-89.24942732255329
Location URL: https://goo.gl/maps/BS3zhMtZt7t2YR2M6
Payment methods: onchain,lightning
Twitter merchant: @superselectos
Twitter submitter: @ElSalvadorVisas
Notes: Chivo web interface
Status: Todo
Created at: 2022-09-23T16:29:09.341Z

**Comment by BitcoinMSW** [comment]
https://www.openstreetmap.org/edit#map=19/13.70685/-89.24943

Added point with basic info and bitcoin tags
