### ISSUE TITLE
Verein Wunder Baden

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#101]
Merchant name: Verein Wunder Baden
Address: Theaterplatz 8a, 5400 Baden
Lat: 47.47409597895909
Long: 8.308925628662111
OSM: https://www.openstreetmap.org/edit#map=19/47.47409597895909/8.308925628662111
Location URL: https://www.wunderbaden.ch/
Payment methods: lightning
Twitter merchant: 
Twitter submitter: 
Notes: 
Status: Todo
Created at: 2022-09-23T16:24:57.431Z

**Comment by f321x** [comment]
already added
