### ISSUE TITLE
villas jucanya

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#102]
Merchant name: villas jucanya
Address: Playa Los Salpores, Calle Frente al Lago, Panajachel 07010, Guatemala
Lat: 
Long: 
OSM: 
Location URL: https://www.google.com/maps/place/VILLAS+JUCANYA/@14.7332817,-91.1542894,17z/data=!3m1!4b1!4m9!3m8!1s0x85894beccc11433d:0x7ff67fd9b02360fb!5m2!4m1!1i2!8m2!3d14.7332817!4d-91.1542894!16s%2Fg%2F11clmc07x8
Payment methods: lightning
Twitter merchant: 
Twitter submitter: 
Notes: 
Status: Todo
Created at: 2022-09-23T17:05:22.993Z

**Comment by BitcoinMSW** [comment]
https://www.openstreetmap.org/edit?node=3419400201#map=19/14.73340/-91.15430

Bitcoin tags already added. NFA required.
