### ISSUE TITLE
Swat Marketing Ltd

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#103]
Merchant name: Swat Marketing Ltd 
Address: 70 Whichelo Place, Brighton BN2 9XF 
Lat: 
Long: 
OSM: 
Location URL: 
Payment methods: onchain
Twitter merchant: 
Twitter submitter: 
Notes: You've got an old address for swat marketing. 
Status: Todo
Created at: 2022-09-23T18:16:13.032Z
Merchant name: AVIA Tankstelle
Address: Scheuerer Straße 1a, 93096 Köfering
Lat: 
Long: 
OSM: 
Location URL: 
Payment methods: lightning,nfc
Twitter merchant: 
Twitter submitter: @reallooms
Notes: 
Status: Todo
Created at: 2022-09-23T18:22:18.214Z

**Comment by jungusemlevve** [comment]
https://www.openstreetmap.org/edit#map=20/50.83246/-0.13821

https://www.openstreetmap.org/edit#map=20/48.93987/12.20171
