### ISSUE TITLE
ALEFBET

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#104]
Merchant name: ALEFBET - the hebrew letters art gallery 
Address: Via della Reginella 25, Roma RM 
Lat: 41.893514579351205
Long: 12.477359468587542
OSM: https://www.openstreetmap.org/edit#map=19/41.893514579351205/12.477359468587542
Location URL: https://maps.app.goo.gl/ySfniTAmxzZ8E5hx8
Payment methods: onchain,lightning
Twitter merchant: 
Twitter submitter: 
Notes: 
Status: Todo
Created at: 2022-09-24T00:26:03.235Z

**Comment by jungusemlevve** [comment]
https://www.openstreetmap.org/edit#map=20/41.89326/12.47731
