### ISSUE TITLE
Chili Willy

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#106]
Merchant name: Chili Willy
Address: Eichstrasse 1, 5417 Untersiggenthal
Lat: 47.503371060974786
Long: 8.254074454307558
OSM: https://www.openstreetmap.org/edit#map=19/47.503371060974786/8.254074454307558
Location URL: https://www.chiliwilly.ch/
Payment methods: onchain,lightning
Twitter merchant: 
Twitter submitter: 
Notes: World's hottest chillies, meine caliente
Status: Todo
Created at: 2022-09-24T10:08:54.629Z

**Comment by jungusemlevve** [comment]
Keine Infos bei Google oder Maps sowie Kontaktdaten bzw. Webseite, eMail!!
