### ISSUE TITLE
Adding Location Category

### ISSUE THREAD

**Issue by alexjrlewis** [teambtcmap/btcmap-data#119]
Should add new field to specify the merchant type, i.e. bookstore, coffee shop, bar, etc. Suggested field name is Merchant Name
and could potentially be a choice field.

**Comment by dadofsambonzuki** [comment]
Yes we should do this, but I think it should be free text for the Noob form.

The OSM editor has a category search field that looks through the vast list OSM has.

This is addressed in [this issue](https://github.com/teambtcmap/btcmap.org/issues/35).

**Comment by secondl1ght** [comment]
Thanks for the feedback @alexjrlewis, this is now added.
