### ISSUE TITLE
Sentinel Vaults - Safe Deposit Boxes 

### ISSUE THREAD

**Issue by donaldevine** [teambtcmap/btcmap-data#124]
### Merchant location

https://btcmap.org/map?lat=53.3329433&long=-6.2435879

### Edit link

https://www.openstreetmap.org/edit?node=2781513612

### Outdated information

This business does not accept sats, it is spam.

### Current information

This business does not accept sats, it is spam.

### How did you verify this?

I checked their website.

**Comment by Martin-1997** [comment]
I removed the payment:bitcoin=yes tag, as it is outdated anyway:
https://www.openstreetmap.org/changeset/126734458
