### ISSUE TITLE
Austin, TX

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#132]
https://twitter.com/OshiApp/status/1562461145327599618

**Comment by dadofsambonzuki** [comment]
15 verified locations need adding from the Twitter thread.

Comment with the names of the places that you have added.

**Comment by bubelov** [comment]
Place 1 (3 forks) was already added: https://www.openstreetmap.org/node/1481364381

**Comment by bubelov** [comment]
Place 2 (The Meteor) existed on OSM, added Bitcoin tags: https://www.openstreetmap.org/changeset/129325968

**Comment by bubelov** [comment]
Place 3 (Shiners Saloon) was already added: https://www.openstreetmap.org/node/1481721326

**Comment by bubelov** [comment]
Place 4 (Happy Lobster) shouldn't be added, too many red flags imo

**Comment by bubelov** [comment]
Place 5 (The Ocean Lab) did not exist on OSM, added: https://www.openstreetmap.org/changeset/129326696

**Comment by bubelov** [comment]
Place 6 (Cantina 512) did not exist on OSM, added: https://www.openstreetmap.org/changeset/129350393

**Comment by bubelov** [comment]
Place 7 (Quezzas) did not exist on OSM, added: https://www.openstreetmap.org/changeset/130514112

**Comment by bubelov** [comment]
Place 8 (The Tipsy Alchemist) was already added: https://www.openstreetmap.org/node/3825447599

**Comment by bubelov** [comment]
Place 9 (Mr. Sandwich) did not exits on OSM, added: https://www.openstreetmap.org/node/10300617011

**Comment by bubelov** [comment]
Place 10 (Meat & Bread) was already added, but didn't have Bitcoin tags so I added them: https://www.openstreetmap.org/node/7925574095

**Comment by jakubszwedo** [comment]
Place 11 was on a map
Added place 12, 13
14 is a service (added a seperate issue)
15 added bitcoin tags to one, added another location which was not on a map
16 is a aservice (added a seperate issue)
