### ISSUE TITLE
Planet Earth Sphere

### ISSUE THREAD

**Issue by stakingpoolspace** [teambtcmap/btcmap-data#140]
### Merchant location

https://btcmap.org/map?lat=50.8524209&long=5.6852958

### Edit link

https://www.openstreetmap.org/edit?node=2566038210

### Outdated information

The domain no longer exists

### Current information

I can find no current information about Planet Earth Sphere

### How did you verify this?

- I opened the link
- Google only returns sites that still show the coordinates, but no information about the organization
- Can't find Planet Earth Sphere on Google maps

**Comment by jmann6** [comment]
Removed bad data https://www.openstreetmap.org/changeset/126899439
