### ISSUE TITLE
klikaid.com

### ISSUE THREAD

**Issue by stakingpoolspace** [teambtcmap/btcmap-data#142]
### Merchant location

https://btcmap.org/map?lat=39.4656544&long=-0.3541383

### Edit link

https://www.openstreetmap.org/edit?node=2389036610

### Outdated information

Domain is no longer valid
Looks like the entity no longer exists

### Current information

None

### How did you verify this?

- Domain no longer functions
- No Twitter updates after 2016/2017

**Comment by dadofsambonzuki** [comment]
Hey @stakingpoolspace - would you like to be added to this repo so you can manage issues?

Feel free to jump into OSM and make those delations you see fit and update here.

**Comment by bubelov** [comment]
No website, no info on Google Maps, deleting
