### ISSUE TITLE
One&Lux (O&L) Apartments

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#15]
Merchant name: One&Lux (O&L) Apartments
Address: Calle Muñoz Olive 1
Location URL: http://www.oneandlux.com/
Business type: 
Payment methods: onchain,lightning,nfc
Twitter handle: @oneandlux
Notes: Touristic Accommodations (serviced apartments)
Status: Todo
Created at: 2022-09-15T09:38:39.624Z

**Comment by dadofsambonzuki** [comment]
Emailed the business as we need specific locations for all their rental apartments.

**Comment by bubelov** [comment]
I think we shouldn't add those places

https://wiki.openstreetmap.org/wiki/Cryptocurrency

> Based on the principles of the openstreetmap practices, we only tag locations that accept the cryptocurrency at the physical location itself.

**Comment by dadofsambonzuki** [comment]
I agree.
