### ISSUE TITLE
Verify legacy places in your city

### ISSUE THREAD

**Issue by bubelov** [teambtcmap/btcmap-data#1611]
[Tokyo](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3ATokyo%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=35.68965;139.84291;11)
[Delhi](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3ADelhi%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=28.61828;77.32727;11)
[Shanghai](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3AShanghai%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=31.25449;121.49849;11)
[São Paulo](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3AS%C3%A3o%20Paulo%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=-23.62691;-46.51199;10)
[Mexico City](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3AMexico%20City%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=19.3999;-99.04861;11)
[Austin](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3AAustin%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=30.32547;-97.63962;11)
[San Francisco](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3ASan%20Francisco%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=37.74927;-122.33448;12)
[London](https://maps.mail.ru/osm/tools/overpass/?Q=%7B%7BgeocodeArea%3ALondon%7D%7D-%3E.a%3B%0Anwr(area.a)%5B'payment%3Abitcoin'%3Dyes%5D%3B%0Aout%3B&C=51.55402;-0.07072;11)

Don't have your city in the list? Leave a comment and we'll add it.

**Comment by shankspony07** [comment]
London?

**Comment by bubelov** [comment]
> London?

Added. There are 19 unverified places in London.
