### ISSUE TITLE
Snapsacks

### ISSUE THREAD

**Issue by 12cbQLTFMXRnSzktFkuoG3eHoMeFtpTu3S** [teambtcmap/btcmap-data#165]
### Merchant location

https://btcmap.org/map?lat=14.630348&long=121.0030053

### Edit link

https://www.openstreetmap.org/edit?node=3070899311

### Outdated information

Shop is closed and no longer in business

### Current information

shop is still listed in BTC Map

### How did you verify this?

![image](https://user-images.githubusercontent.com/85469075/193228824-de3ce667-4018-4d8a-a17c-421f8b5afbbe.png)

**Comment by dadofsambonzuki** [comment]
Removed from OSM.
