### ISSUE TITLE
BBQ Olympic

### ISSUE THREAD

**Issue by jakubszwedo** [teambtcmap/btcmap-data#1811]
https://www.bbqolympic.com/
Catering services
lightning, onchain (uses Bitcoin People from Italy)

Sources: 
https://www.bitcoinpeople.it/attivita-accettano-pagamenti-in-bitcoin/
https://www.instagram.com/p/CeMPa2AIaf2/

**Comment by dadofsambonzuki** [comment]
Added to wiki.
