### ISSUE TITLE
Elementi Zen Marina

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#19]
Merchant name: Elementi Zen Marina
Address: The Zen Tower Dubai Marina
Location URL: https://maps.app.goo.gl/EPCC6ku45KFKKdep7
Business type: 
Payment methods: onchain,lightning
Twitter handle: 
Notes: Amazing 2 br apartment with sea view available for rent. It is located on higher floor and is rented with no furniture for 1 year contract. For more location contact +38167105622
Status: Todo
Created at: 2022-09-19T09:47:22.503Z

**Comment by f321x** [comment]
added
