### ISSUE TITLE
Schedule job to review locations

### ISSUE THREAD

**Issue by BenGWeeks** [teambtcmap/btcmap-data#206]
A number of the data sources look to be old businesses that are no longer running.

Perhaps create a scheduled job that runs and reviews the locations and tags them for review if the website is not running for example, or a title is missing etc.

**Comment by secondl1ght** [comment]
We already have the information of when a location was last updated. We will be adding a checkmark by the Survey Date to ones that have been updated in the past year to give an indication that it is more likely to be up to date. I think anything with a Survey Date of over a year old can be assumed it needs some current validation.

**Comment by secondl1ght** [comment]
Closing this unless there is any more feedback on the proposed solution.
