### ISSUE TITLE
IBEX Mercardo - ALL

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#210]

**Comment by BitcoinMSW** [comment]
Happy to work my way through these 👍

**Comment by BitcoinMSW** [comment]
1. https://www.openstreetmap.org/edit#map=20/25.78502/-80.13074
2. https://www.openstreetmap.org/edit#map=20/25.86046/-80.12008
3. Boho Hunter Wynwood - permanently closed on Google so not added
4. https://www.openstreetmap.org/edit#map=20/25.80271/-80.19552
5. https://www.openstreetmap.org/edit#map=20/25.79993/-80.20043
6. https://www.openstreetmap.org/edit#map=19/25.76850/-80.19058

**Comment by BitcoinMSW** [comment]
7. https://www.openstreetmap.org/edit#map=20/25.78730/-80.14406
8. https://www.openstreetmap.org/edit#map=20/25.79840/-80.19885

**Comment by BitcoinMSW** [comment]
9. https://www.openstreetmap.org/edit#map=19/25.79102/-80.14070
10. HeartLand - permanently closed on Google maps so not added
11. https://www.openstreetmap.org/edit#map=20/25.79743/-80.21570
12. https://www.openstreetmap.org/edit#map=20/25.76740/-80.19646
13. https://www.openstreetmap.org/edit#map=20/25.79963/-80.19958
14. https://www.openstreetmap.org/edit#map=20/25.73352/-80.26045
15. https://www.openstreetmap.org/edit#map=20/25.79069/-80.14019
16. https://www.openstreetmap.org/edit#map=20/25.80007/-80.19383
17. https://www.openstreetmap.org/edit#map=20/25.85003/-80.19269

**Comment by BitcoinMSW** [comment]
18. https://www.openstreetmap.org/edit#map=19/25.72848/-80.24194
19. https://www.openstreetmap.org/edit#map=20/25.79962/-80.19922
20. https://www.openstreetmap.org/edit#map=20/25.88661/-80.13077
21. https://www.openstreetmap.org/edit#map=20/25.77416/-80.13615
22. https://www.openstreetmap.org/edit#map=20/25.79141/-80.13002
23. https://www.openstreetmap.org/edit#map=20/25.79129/-80.14018

**Comment by BitcoinMSW** [comment]
24. https://www.openstreetmap.org/edit#map=20/25.79964/-80.20147
25. https://www.openstreetmap.org/edit#map=20/25.79608/-80.19781
26. https://www.openstreetmap.org/edit#map=20/26.11858/-80.13765
27. https://www.openstreetmap.org/edit#map=20/25.79343/-80.14288

**Comment by BitcoinMSW** [comment]
28. https://www.openstreetmap.org/edit#map=20/25.86046/-80.12008
29. https://www.openstreetmap.org/edit#map=20/25.76852/-80.19095
30. https://www.openstreetmap.org/edit#map=20/25.72865/-80.26207

**Comment by BitcoinMSW** [comment]
31. https://www.openstreetmap.org/edit#map=20/25.76649/-80.19497
32. https://www.openstreetmap.org/edit#map=20/25.78850/-80.14140
33. https://www.openstreetmap.org/edit#map=20/35.54259/-80.86047
34. https://www.openstreetmap.org/edit#map=20/35.40247/-80.75864

**Comment by BitcoinMSW** [comment]
35. https://www.openstreetmap.org/edit#map=20/35.47656/-80.89290
36. https://www.openstreetmap.org/edit#map=20/42.14547/-70.95477
37. https://www.openstreetmap.org/edit#map=20/42.29081/-71.80570
38. https://www.openstreetmap.org/edit#map=20/25.84516/-80.18825
39. https://www.openstreetmap.org/edit#map=20/25.86661/-80.19330
40. https://www.openstreetmap.org/edit#map=20/25.77419/-80.13525
41. https://www.openstreetmap.org/edit#map=20/39.84529/-75.71622
42. https://www.openstreetmap.org/edit#map=20/25.77480/-80.13632
43. https://www.openstreetmap.org/edit#map=20/30.26709/-97.74350

**Comment by BitcoinMSW** [comment]
48. https://www.openstreetmap.org/edit#map=20/25.79136/-80.13644
49. https://www.openstreetmap.org/edit#map=20/25.79155/-80.13618
50. https://www.openstreetmap.org/edit#map=20/30.25072/-97.75430
51. https://www.openstreetmap.org/edit#map=19/30.65376/-97.00493
52. https://www.openstreetmap.org/edit#map=20/41.84377/-90.18844
53. https://www.openstreetmap.org/edit#map=18/30.64559/-97.02108
54. https://www.openstreetmap.org/edit#map=20/25.79155/-80.13618
55. https://www.openstreetmap.org/edit#map=20/40.58115/-122.39155

**Comment by dadofsambonzuki** [comment]
Wow @BitcoinMSW - you absolute beast!

**Comment by dadofsambonzuki** [comment]
Here are the remaining ones:

[La Cantina](https://www.openstreetmap.org/edit#map=20/30.2836023/-97.7225302)
[Paradise Bistro & Coffee Co](https://www.openstreetmap.org/edit#map=20/32.4420199/-97.7869344)
[Beck's Farmhouse Coffee](https://www.openstreetmap.org/edit#map=20/36.3626427/-86.8871372)
[Wrich Ranches](https://www.openstreetmap.org/edit#map=20/38.6782669/-107.6656075)
[Domino's Pizza](https://www.openstreetmap.org/edit#map=20/13.6917329/-89.2370094)
[Domino's Pizza Constitución](https://www.openstreetmap.org/edit#map=20/13.7212932/-89.2219256)
[Domino's Pizza](https://www.openstreetmap.org/edit#map=20/13.9804409/-89.5595923)
[Domino's Pizza](https://www.openstreetmap.org/edit#map=20/13.474326/-88.1840801)
[Domino's Pizza Plaza Mundo](https://www.openstreetmap.org/edit#map=20/13.6987351/-89.1501699)
[Dominos Pizza Plaza San Jacinto](https://www.openstreetmap.org/edit#map=20/13.6852064/-89.191204)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.6834893/-89.2304682)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.7017231/-89.2312622)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.7092752/-89.209114)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.705211/-89.2099263)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.689101/-89.2402641)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.6835168/-89.2304195)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.475058/-88.1841723)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.705655/-89.2489111)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.4952049/-88.1724166)
[Wendy's](https://www.openstreetmap.org/edit#map=20/13.7007345/-89.2214402)
[Pizza Hut Multiplaza](https://www.openstreetmap.org/edit#map=20/13.679651/-89.249659)
[Pizza Hut](https://www.openstreetmap.org/edit#map=20/13.6827153/-89.2307389)
[Pizza Hut Food Court Lourdes](https://www.openstreetmap.org/edit#map=20/13.728151/-89.360155)
[Pizza Hut](https://www.openstreetmap.org/edit#map=20/13.7146/-89.141018)
[Pizza Hut Metrocentro 11ava. Etapa](https://www.openstreetmap.org/edit#map=20/13.7058629/-89.2126599)
[Pizza Hut](https://www.openstreetmap.org/edit#map=20/13.7090082/-89.210617)
[Pizza Hut](https://www.openstreetmap.org/edit#map=20/13.7024148/-89.229264)
[Pizza Hut](https://www.openstreetmap.org/edit#map=20/13.7014511/-89.2229392)
[Pizza Hut](https://www.openstreetmap.org/edit#map=20/13.5034057/-88.8716979)
[Pizza Hut](https://www.openstreetmap.org/edit#map=20/13.710872/-89.233029)
[China Wok](https://www.openstreetmap.org/edit#map=20/13.9944485/-89.5572978)
[China Wok 10a etapa Metrocentro SS](https://www.openstreetmap.org/edit#map=20/13.7070853/-89.2119083)
[China Wok](https://www.openstreetmap.org/edit#map=20/13.709421/-89.2100284)
[China Wok](https://www.openstreetmap.org/edit#map=20/13.977562/-89.5627456)
[China Wok Food Court Multiplaza](https://www.openstreetmap.org/edit#map=20/13.6790349/-89.248327)
[China Wok](https://www.openstreetmap.org/edit#map=20/13.6834952/-89.231075)
[China Wok Food Court](https://www.openstreetmap.org/edit#map=20/13.6787514/-89.2755655)
[China Wok](https://www.openstreetmap.org/edit#map=20/13.6835975/-89.2226009)
[China Wok Food Court Unicentro Soyapango](https://www.openstreetmap.org/edit#map=20/13.7146166/-89.1409733)
[China Wok Plaza Mundo 1](https://www.openstreetmap.org/edit#map=20/13.6981477/-89.1506543)
[China Wok Santa Tecla](https://www.openstreetmap.org/edit#map=20/13.6730012/-89.2859168)
[China Wok](https://www.openstreetmap.org/edit#map=20/13.977562/-89.5627456)
[China Wok Food Court Unicentro Soyapango](https://www.openstreetmap.org/edit#map=20/13.7146166/-89.1409733)
[China Wok 10a etapa Metrocentro SS](https://www.openstreetmap.org/edit#map=20/13.7070853/-89.2119083)
[China Wok Food Court Multiplaza](https://www.openstreetmap.org/edit#map=20/13.6790349/-89.248327)
[KFC](https://www.openstreetmap.org/edit#map=20/13.7059952/-89.2136163)
[KFC](https://www.openstreetmap.org/edit#map=20/13.6829299/-89.2313385)
[KFC](https://www.openstreetmap.org/edit#map=20/13.6993252/-89.1510265)
[KFC](https://www.openstreetmap.org/edit#map=20/13.6765075/-89.2529552)
[KFC](https://www.openstreetmap.org/edit#map=20/13.6986264/-89.1967002)
[KFC](https://www.openstreetmap.org/edit#map=20/13.6788565/-89.2756443)
[KFC](https://www.openstreetmap.org/edit#map=20/13.4624733/-88.1660493)
[KFC Los Héroes](https://www.openstreetmap.org/edit#map=20/13.7078878/-89.2110963)
[KFC - C.C. UNICENTRO METRÓPOLIS](https://www.openstreetmap.org/edit#map=20/13.7298437/-89.2101511)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.682875/-89.2311213)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.7020354/-89.2351788)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.6945995/-89.243082)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.7024837/-89.229632)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.7055325/-89.2104113)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.6981243/-89.1505669)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.6710939/-89.255054)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.6798504/-89.2489573)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.7063077/-89.2492934)
[Starbucks](https://www.openstreetmap.org/edit#map=20/13.7082184/-89.241325)
[Subway Autopista Sur](https://www.openstreetmap.org/edit#map=20/13.6833634/-89.2223961)
[Subway San Luis](https://www.openstreetmap.org/edit#map=20/13.7152239/-89.2116204)
[Subway](https://www.openstreetmap.org/edit#map=20/13.6695554/-89.2276618)
[Subway El Platillo](https://www.openstreetmap.org/edit#map=20/13.678485/-89.2629402)
[Puro Surf Hotel & Performance Academy](https://www.openstreetmap.org/edit#map=20/13.4962778/-89.437828)
[Puro Surf Academy San Blas](https://www.openstreetmap.org/edit#map=20/13.4865815/-89.3575808)
[Puro Surf Hotel and Academy](https://www.openstreetmap.org/edit#map=20/13.494141/-89.38242)
[Cadejo Brewing Company](https://www.openstreetmap.org/edit#map=20/13.6937465/-89.2352294)
[Cadejo Brewing Company](https://www.openstreetmap.org/edit#map=20/13.6937465/-89.2352294)
[Cadejo Brewing Company - La Libertad](https://www.openstreetmap.org/edit#map=20/13.4939079/-89.3997802)
[Cadejo Brewing Company. C. C. Santa Rosa](https://www.openstreetmap.org/edit#map=20/13.6782296/-89.2992307)
[Cadejo Brewing Company Santa Elena](https://www.openstreetmap.org/edit#map=20/13.6616367/-89.2493013)
[Eva Innocenti](https://www.openstreetmap.org/edit#map=20/13.69819/-89.2411)
[Blush Salon Nailbar - Zona Rosa](https://www.openstreetmap.org/edit#map=20/13.690198/-89.240056)
[Blush Salon Nailbar - Metrocentro](https://www.openstreetmap.org/edit#map=20/13.706094/-89.211949)
[Blush Salon Nailbar - Santa Elena](https://www.openstreetmap.org/edit#map=20/13.662393/-89.2562359)
[Blush - Galerias](https://www.openstreetmap.org/edit#map=20/13.7023056/-89.2299765)
[Blush Salon Nailbar - Zona Rosa](https://www.openstreetmap.org/edit#map=20/13.690198/-89.240056)
[Laborable](https://www.openstreetmap.org/edit#map=20/13.6919834/-89.2375948)
[Bambu City Center](https://www.openstreetmap.org/edit#map=20/13.6919118/-89.2378043)
[Merkato](https://www.openstreetmap.org/edit#map=20/13.6879737/-89.2428324)
[Le Croissant San Benito](https://www.openstreetmap.org/edit#map=20/13.688758/-89.241168)
[Le Croissant Insigne](https://www.openstreetmap.org/edit#map=20/13.6920512/-89.2382608)
[Le Croissant Multiplaza](https://www.openstreetmap.org/edit#map=20/13.6792746/-89.2484934)
[Le Croissant Los Sueños](https://www.openstreetmap.org/edit#map=20/13.6510776/-89.2806365)
[Le Croissant - Oficina Central](https://www.openstreetmap.org/edit#map=20/13.6711765/-89.2594418)
[Clinical laboratories Max Bloch](https://www.openstreetmap.org/edit#map=20/13.7017947/-89.2373549)
[MaxBloch Clínicas Médicas](https://www.openstreetmap.org/edit#map=20/13.7051119/-89.2041917)
[Clinical laboratories Max Bloch](https://www.openstreetmap.org/edit#map=20/13.7088774/-89.2019258)
[MaxBloch Villavicencio](https://www.openstreetmap.org/edit#map=20/13.7030096/-89.245903)
[MaxBloch Santa Elena](https://www.openstreetmap.org/edit#map=20/13.66777/-89.2561501)
[Subway](https://www.openstreetmap.org/edit#map=20/13.9202687/-89.8485153)
[Subway UFG](https://www.openstreetmap.org/edit#map=20/13.6984975/-89.2200322)
[Subway](https://www.openstreetmap.org/edit#map=20/13.7151856/-89.1411706)
[Subway Texaco Británica](https://www.openstreetmap.org/edit#map=20/13.6718063/-89.2758808)
[Subway Texaco Masferrer](https://www.openstreetmap.org/edit#map=20/13.70566/-89.2494076)
[Subway](https://www.openstreetmap.org/edit#map=20/13.7076128/-89.2405051)
[Subway](https://www.openstreetmap.org/edit#map=20/13.680034/-89.2406717)
[Subway](https://www.openstreetmap.org/edit#map=20/13.7098352/-89.2032503)
[Viva Espresso](https://www.openstreetmap.org/edit#map=20/13.6869455/-89.245473)
[OPI Nail Bar - El Paseo](https://www.openstreetmap.org/edit#map=20/13.7016913/-89.2353196)
[OPI Nail Bar - San Benito](https://www.openstreetmap.org/edit#map=20/13.6956331/-89.2319288)
[OPI Nail Bar - Multiplaza](https://www.openstreetmap.org/edit#map=20/13.679356/-89.248704)
[OPI Nail Bar - Plaza Atrio](https://www.openstreetmap.org/edit#map=20/13.6944796/-89.2411462)
[O.P.I. Nail Bar](https://www.openstreetmap.org/edit#map=20/13.6769375/-89.2542615)
[Mercar](https://www.openstreetmap.org/edit#map=20/13.69171/-89.2178)
[Bennigan's](https://www.openstreetmap.org/edit#map=20/13.67675/-89.25436)
[Olive Garden](https://www.openstreetmap.org/edit#map=20/13.67674/-89.254288)
[Benihana](https://www.openstreetmap.org/edit#map=20/13.7020713/-89.2348013)
[Wings El Salvador](https://www.openstreetmap.org/edit#map=20/13.6802279/-89.2482818)
[Soho Japanese Fusion El Salvador](https://www.openstreetmap.org/edit#map=20/13.6801956/-89.248323)
[Omnisport](https://www.openstreetmap.org/edit#map=20/13.6988992/-89.1967857)
[Omnisport Plaza Mundo 4a Etapa](https://www.openstreetmap.org/edit#map=20/13.6991328/-89.1515539)
[El Centro Textil](https://www.openstreetmap.org/edit#map=20/13.6982704/-89.1923398)
[Sunzal Cafe](https://www.openstreetmap.org/edit#map=20/13.4935541/-89.3900146)
[Casa de Mar Hotel And Villas](https://www.openstreetmap.org/edit#map=20/13.4937496/-89.3904571)
[Ta´Cool - Plaza Mundo Soyapango](https://www.openstreetmap.org/edit#map=20/13.6977812/-89.1515313)
[Taco club](https://www.openstreetmap.org/edit#map=20/13.698053/-89.151197)
[Taco Club Galerias](https://www.openstreetmap.org/edit#map=20/13.7022918/-89.2292528)
[Taco club](https://www.openstreetmap.org/edit#map=20/13.698053/-89.151197)
[Taco Club • Mall Marsella](https://www.openstreetmap.org/edit#map=20/13.7946099/-89.3457756)
[Ta´Cool - Plaza Mundo Soyapango](https://www.openstreetmap.org/edit#map=20/13.6977812/-89.1515313)
[Ta`Cool • El Encuento San Martín](https://www.openstreetmap.org/edit#map=20/13.721974/-89.0689072)
[Pizque](https://www.openstreetmap.org/edit#map=20/13.4444494/-89.057861)
[El Salvador International Airport](https://www.openstreetmap.org/edit#map=20/13.4447038/-89.0570087)
[CE IGNACIO PACHECO CASTRO](https://www.openstreetmap.org/edit#map=20/13.6616996/-89.1858285)
[Funky House](https://www.openstreetmap.org/edit#map=20/13.7066913/-89.2424418)
["Dr. Max Bloch" Central Laboratory](https://www.openstreetmap.org/edit#map=20/13.700009/-89.2075251)
[Ye Olde Orchard Pub & Grill](https://www.openstreetmap.org/edit#map=20/45.3618227/-73.7473807)
[Ye Olde Orchard Pub & Grill](https://www.openstreetmap.org/edit#map=20/45.5134983/-73.5727146)
[Ye Olde Orchard Pub & Grill](https://www.openstreetmap.org/edit#map=20/45.4760896/-73.6226207)
[Ye Olde Orchard Pub and Grill](https://www.openstreetmap.org/edit#map=20/45.4972692/-73.5734084)
[Ye Olde Orchard Pub & Grill](https://www.openstreetmap.org/edit#map=20/45.428634/-73.827223)
[Realworld Paragliding](https://www.openstreetmap.org/edit#map=20/14.7431208/-91.157227)
[The Bark by San Roque](https://www.openstreetmap.org/edit#map=20/14.590308/-90.492745)
[Restaurante Lena’s Atlantis](https://www.openstreetmap.org/edit#map=20/14.7441161/-91.1559501)
[Cova Beer & Spirits](https://www.openstreetmap.org/edit#map=20/14.5924987/-90.4916427)
[¨La Petrona¨ Vinos Naturales](https://www.openstreetmap.org/edit#map=20/14.6211471/-90.5136687)
[Flatbox, S.A.](https://www.openstreetmap.org/edit#map=20/14.6220492/-90.5143382)
[Recording Box](https://www.openstreetmap.org/edit#map=20/14.6221618/-90.5130775)
[Adra Hostel](https://www.openstreetmap.org/edit#map=20/14.5572227/-90.730736)
[Santo Spirito](https://www.openstreetmap.org/edit#map=20/14.5564817/-90.7316662)
[CrypStation](https://www.openstreetmap.org/edit#map=20/-34.613647/-58.3655097)
[Superanfibio](https://www.openstreetmap.org/edit#map=20/-31.3717384/-64.2378029)
[Superanfibio Villa Allende](https://www.openstreetmap.org/edit#map=20/-31.2867907/-64.2945741)
[Odontologia Integral](https://www.openstreetmap.org/edit#map=20/-31.2944197/-64.2993142)
[Mc Peluqueria](https://www.openstreetmap.org/edit#map=20/-31.412616/-64.16558)
[CheFrida](https://www.openstreetmap.org/edit#map=20/-31.424732/-64.191433)
[Casper Fermentables - Bagels, Kombucha, Sourdough](https://www.openstreetmap.org/edit#map=20/30.2326232/-97.8113564)
[Los Fenicios - Vinoteca Licorería](https://www.openstreetmap.org/edit#map=20/-31.4219769/-64.1807873)

**Comment by bubelov** [comment]
This issue mentioned Google, and we were recently informed that adding any data from Google is not allowed: https://www.openstreetmap.org/copyright

> OSM contributors are reminded never to add data from any copyrighted sources (e.g. Google Maps or printed maps) without explicit permission from the copyright holders. 

I am not a lawyer, it's probably fine to use Google Maps to NOT to add something, since it would be quite a stretch to consider inaction as a copyright infringement, but still, it's better to avoid it, because it gives people a false impression that our data source is Google Maps and no

**Comment by dadofsambonzuki** [comment]
Understood.

To be clear Google Maps is not the source of this information, it is the payment provider IBEX themselves.

**Comment by bubelov** [comment]
Is it still in progress?

**Comment by dadofsambonzuki** [comment]
They still need to be added, yes.

**Comment by bubelov** [comment]
Done
