### ISSUE TITLE
Pick N Pay Stores - South Africa

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#2409]
### Background

[Pick N Pay](https://en.wikipedia.org/wiki/Pick_n_Pay_Stores) have announced rollout of their BTC payment pilot to their entire network of stores.

Evidence:

[Crypto Converted announcement](https://twitter.com/CryptoConverted/status/1620745811582939136)
[news.bitcoin.com](https://news.bitcoin.com/south-african-retailer-pick-n-pay-now-accepting-payments-via-btc-at-all-its-stores/)
[Coin Telegraph](https://cointelegraph.com/news/retail-giant-pick-n-pay-to-accept-bitcoin-in-1-628-stores-across-south-africa)

This is powered by [Crypto Converted](https://twitter.com/CryptoConverted).

We have already tagged the pilot stores (circa 20) and there is a total of circa. 1900.

There are currently 433 PNP stores in OSM, as shown by [this overpass query](https://overpass-turbo.eu/s/1qT2).

![Screenshot 2023-02-02 at 10 31 09](https://user-images.githubusercontent.com/87125117/216314194-c6a324d8-7a1d-4edf-974e-a948187c3f50.png)

### Proposal

- [x] Engage with the local OSM mods to do an automated edit of the current PNP locations to add the appropriate BTC tags. [Engagement thread here](https://community.openstreetmap.org/t/pick-n-pay-stores-bitcoin/8771).
- [ ] Liaise with PNP & Crypto Converted to get the full list of PNP locations.
- [ ] Engage with the local OSM mods to do an automated import of the new PNP locations.

**Comment by dadofsambonzuki** [comment]
I have exchanged messages with Crypto Converted today and they are asking PNP for a current list of store locations.

**Comment by bsn21m** [comment]
I could only find and process about 12 pieces of Pck N Pay markets. The following tags were deposited: currency:XBT=yes, payment:onchain=yes, payment:lightning=yes, payment:lightning_contactless=no, check_date:currency:XBT=yyyy-mm-dd

**Comment by bubelov** [comment]
I think we already imported those stores long time ago
