### ISSUE TITLE
Bic Camera Stores - Japan.

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#2410]
### Background

[Bic Camera](https://en.wikipedia.org/wiki/Pick_n_Pay_Stores) accept BTC across their entire network of stores.

Evidence:

* [Bic Camera Website](https://www.biccamera.com/bc/c/info/payment/bitcoin.jsp)
* [Video of in-store transaction, 2022](https://www.youtube.com/shorts/fNXg5lHZ6t0)

None of the (circa 82) stores have been tagged.

There are currently 51 Bic Camera stores in OSM, as shown by [this overpass query](https://overpass-turbo.eu/s/1qTv).

![Screenshot 2023-02-02 at 12 43 46](https://user-images.githubusercontent.com/87125117/216328259-e69039e7-2c8e-4a83-be13-1659fc024a4a.png)

### Proposal

- [x] ~~Engage with the local OSM mods to do an automated edit of the current Bic Camera locations to add the appropriate BTC tags.~~ @bsn21m manually add them!
- [ ] Liaise with Bic Camera to get the full list of store locations. _IN PROGRESS_
- [ ] Engage with the local OSM mods to do an automated import of the new Bic locations.

**Comment by bsn21m** [comment]
Hello, are the nodes updated once at night and the edited ones removed?

**Comment by bubelov** [comment]
> Hello, are the nodes updated once at night and the edited ones removed?

Do you mean Overpass queries? It's almost real time, I don't think it's supposed to lag by more than a minute

**Comment by bubelov** [comment]
Here is a slightly simplified query:

```
nwr["brand:wikidata"="Q4903531"];
out;
```

**Comment by bsn21m** [comment]
The way I see it, I have edited/finished the locations from the maps. Please give me a quick review. I wonder if we can close it?

**Comment by bubelov** [comment]
Yea, I think it's better if we close this issue since it doesn't really describe a single task. We can open a separate issue regarding getting a full list of Bic Camera locations, if someone is willing to add them to OSM. Personally, I'm not OK with adding anything else since I don't know how the payment flow looks like, and it's better to assign the rest of the work to locals. 

Feel free to re-open if you don't like this plan, I'm just trying to keep the task list clean and actionable. Removing old discussions makes it easier to grasp for new mappers.

**Comment by dadofsambonzuki** [comment]
Wow, you did it manually @bsn21m?

That plan was too automate, but looks like you got there first!

I will re-open as we are trying to source a full list of Bic locations as per the Issue description.

**Comment by dadofsambonzuki** [comment]
I've just added the remaining 2.

I will seek a full list of locations from Bic Camera Stores via the Tokyo Citadel community.

**Comment by aki-mizu** [comment]
Thank you so much for you guys working on this. 
Unfortunately, Bic camera will no longer accept bitcoin payment starting from March 22nd this year, citing enhancement of KYC rules.
From March 22nd, users who want to pay with bitcoin need to pay from their Bitflyer account instead which requires KYC and Japanese residency.
Once again, thank you for all the hard work, but kindly remove all the Bic camera stores on btcmap if possible. 
https://www.biccamera.com/bc/c/info/payment/bitcoin.jsp

**Comment by dadofsambonzuki** [comment]
We're definitely at the 'then they fight you stage'.

**Comment by dadofsambonzuki** [comment]
@bubelov - did you remove all of these?

**Comment by bubelov** [comment]
Yep
