### ISSUE TITLE
Elektra Stores - Mexico

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#2531]
### Background

[Elektra](https://www.elektra.mx/) stores in Mexico now accept Bitcoin.

Evidence:

- [Reuters](https://www.reuters.com/markets/us/mexican-retailer-grupo-elektra-embraces-bitcoin-payments-2021-12-17/)
- [Euronews](https://www.euronews.com/next/2021/12/17/mexico-elektra-bitcoin)
- [Mexico News Daily](https://mexiconewsdaily.com/news/elektra-becomes-first-retail-chain-to-accept-bitcoin/)
- [Tweet from the owner](https://twitter.com/RicardoBSalinas/status/1471563667439120384)

There are currently 164 Elektra stores in OSM according to this [overpass query](https://overpass-turbo.eu/s/1rcS).

![Elektra Locations](https://user-images.githubusercontent.com/87125117/218092529-239b95f9-7e4b-45bc-ac93-9ca987249887.png)

### Proposal

- [x] Engage with the local OSM mods to do an automated edit of the current Elektra locations to add the appropriate BTC tags. [Engagement thread here](https://community.openstreetmap.org/t/elektra-stores-bitcoin/8806).
- [ ] Liaise with Elektra to get the full list of locations.
- [x] Engage with the local OSM mods to do an automated import of the new Elektra locations.

**Comment by dadofsambonzuki** [comment]
Emailed Elektra and contacted Don (owner) on twitter.

Opened a discussion on the Mexican OSM forum.

**Comment by dadofsambonzuki** [comment]
Local Mexican OSM moderator is going to light up circa. 3000 Elektra locations. 👀

**Comment by bubelov** [comment]
Any news on that? I thing we discussed it once and we figured out that those stores don't really accept bitcoins (they had some bs limits and/or KYC)

**Comment by dadofsambonzuki** [comment]
Valid locations.

I checked with the Mexican OSM mod and all current Elektra stores have been tagged, although not all Elektra stores have been added to OSM.
