### ISSUE TITLE
BC Studios

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#26]
Merchant name: BC Studios
Address: De Jagerstraat 79A, 3022VN Rotterdam
Location URL: https://www.google.com/search?q=bc%20studio%20rotterdam&sxsrf=ALiCzsaMldFiBsqvUPYch5glB0IJ6lRpJA:1663589654828&source=hp&ei=E10oY6WgE8q4kgWo2ZTIDQ&iflsig=AJiK0e8AAAAAYyhrI7IEdO1s5eu6KaNuFPwAUpSvu-IG&ved=2ahUKEwjm9LWz6qD6AhWSLewKHUjaDNIQvS56BAgMEAE&uact=5&oq=bc+studio+rotterdam&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEOgQIIxAnOgYIIxAnEBM6BAgAEEM6EAguELEDEMcBENEDENQCEEM6CwgAEIAEELEDEIMBOhEILhCABBCxAxCDARDHARDRAzoGCAAQChBDOgsILhCABBDHARCvAToRCC4QgAQQsQMQgwEQxwEQrwE6CAgAELEDEIMBOggIABCABBCxAzoOCC4QsQMQgwEQxwEQrwE6CwguEIAEEMcBENEDOgUILhCABDoFCAAQywE6BggAEB4QFlAAWIEVYMsWaABwAHgAgAGRAYgBvA6SAQQxMy42mAEAoAEB&sclient=gws-wiz&tbs=lf:1,lf_ui:2&tbm=lcl&rflfq=1&num=10&rldimm=2187099182519846133&lqi=ChNiYyBzdHVkaW8gcm90dGVyZGFtGRYS2ke_hNPQWhUiE2JjIHN0dWRpbyByb3R0ZXJkYW2SARJ1bmlzZXhfaGFpcmRyZXNzZXKqAREQASoNIgliYyBzdHVkaW8oAg&sa=X&rlst=f#rlfi=hd:;si:2187099182519846133,l,ChNiYyBzdHVkaW8gcm90dGVyZGFtGRYS2ke_hNPQWhUiE2JjIHN0dWRpbyByb3R0ZXJkYW2SARJ1bmlzZXhfaGFpcmRyZXNzZXKqAREQASoNIgliYyBzdHVkaW8oAg;mv:[[51.9478614,4.4976845],[51.904841999999995,4.4280229]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2
Business type: 
Payment methods: onchain,lightning
Twitter handle: 
Notes: https://www.bcstudios.nl/
Status: Todo
Created at: 2022-09-19T12:15:03.354Z

**Comment by Martin-1997** [comment]
Done:
https://www.openstreetmap.org/changeset/126737201
