### ISSUE TITLE
Imprint Digital

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#28]
Merchant name: Imprint Digital
Address: 815 14th St SW
Location URL: https://www.google.com/maps/place/Imprint+Digital/@40.3792551,-105.0902667,15z/data=!4m2!3m1!1s0x0:0xc3830d777991a1a4?sa=X&ved=2ahUKEwj9n7C_paH6AhW7gmoFHUATAuMQ_BJ6BAhOEB8
Business type: 
Payment methods: onchain,lightning
Twitter handle: @imprintdigi
Notes: Digital Marketing Agency focused on Bitcoin only companies, small businesses, and early growth stage companies.

https://imprint-digital.com/
+19705184491
Status: Todo
Created at: 2022-09-19T16:39:46.557Z

**Comment by Martin-1997** [comment]
Done:
https://www.openstreetmap.org/changeset/126736925#map=19/40.37915/-105.09058
