### ISSUE TITLE
Breizh Bitcoin

### ISSUE THREAD

**Issue by JeanlChristophe** [teambtcmap/btcmap-data#2862]
Is it possible to add the city of Nantes and the department (Loire Atlantique) to the region of Brittany please? Nantes is part of Breizh Bitcoin.

Thanks.

https://github.com/teambtcmap/btcmap-data/issues/2576

**Comment by JeanlChristophe** [comment]
Hi,

No improvement on this ticket?
You have to distinguish between the [Brittany](https://en.wikipedia.org/wiki/Brittany) and the [administrative district](https://en.wikipedia.org/wiki/Brittany_(administrative_region)) that separated Nantes [in 1941 during the Nazi occupation](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000000866992). Unless you are state suckers?

**Comment by dadofsambonzuki** [comment]
> Unless you are state suckers?

Hahah, definitely not. Sorry, this didn't have the community tag and so didn't get the attention it required.

I will re-open #2576 to change the boundary.

**Comment by JeanlChristophe** [comment]
Ahah thanks @dadofsambonzuki
