### ISSUE TITLE
 Straight-up Digital Marketing

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#29]
Merchant name: Straight-up Digital Marketing
Address: Stony Plain, AB
Location URL: https://www.straightupdigital.ca/
Business type: 
Payment methods: onchain,lightning
Twitter handle: 
Notes: I would prefer not to give an exact address if possible? I offer services such as Website Design, SEO, and Digital Marketing, but it's all remote and online, and not a physical storefront.
Status: Todo
Created at: 2022-09-19T17:06:02.421Z

**Comment by Martin-1997** [comment]
If it is not a physical store or office, it is not going to be added to OSM.

**Comment by bluefuze** [comment]
Hi there, this is the actual business owner that submitted my location. I am a legit business, but I’m service based. I am a Web Designer & Marketer that works from home. My home is my office. I don’t want people showing up to my home as if I was a storefront. But I do accept BTC & Lightning. I can provide my address if I must, but I’d rather not. Possible?

**Comment by dadofsambonzuki** [comment]
Not really, this is an OSM thing.

We'll soon be launching a services directory that will be more suited to
service provision without an address.
