### ISSUE TITLE
Bitcoin for Humans

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#30]
Merchant name: Bitcoin for Humans
Address: Cathedral Avenue, Perth, 6000
Location URL: 
Business type: 
Payment methods: onchain
Twitter handle: @bitcoinfh
Notes: bitcoinforhumans.com
Bitcoin advisory, services, consulting and free newsletter.
Status: Todo
Created at: 2022-09-20T01:06:46.270Z

**Comment by Martin-1997** [comment]
@dadofsambonzuki from where do you have information about that? It does not seem to have a physical presence. Unfortunately I cannot message the orgranization on Twitter.

**Comment by dadofsambonzuki** [comment]
This was just me importing data from our form.

Check their website?

**Comment by Martin-1997** [comment]
on the website there is no hint for a physical presence, so I am going to close the issue without adding anything
