### ISSUE TITLE
Rennes

### ISSUE THREAD

**Issue by JeanlChristophe** [teambtcmap/btcmap-data#3252]
This request has been indicated as implemented, ticket closed, however no changes have been made.

https://github.com/teambtcmap/btcmap-data/issues/3012

Community name: Rennes
Location: Rennes, Ille-et-Vilaine, Bretagne, France métropolitaine, France
GeoJSON: https://geojson.easify.de/?search=Rennes%2C%20Ille-et-Vilaine%2C%20Bretagne%2C%20France%20m%C3%A9tropolitaine%2C%20France
Icon URL: https://search.brave.com/images?origin=search&q=bitcoin+logo&source=web&img=0
Lightning:
Social links: Website : https://breizhbitcoin.com/
Email : [contact@breizhbitcoin.bzh](mailto:contact@breizhbitcoin.bzh)
Twitter : https://twitter.com/BreizhBitcoin
Discord : discord.gg/gFVe2HcUpw
Community leader contact: [contact@breizhbitcoin.bzh](mailto:contact@breizhbitcoin.bzh)
Notes: Breizh Bitcoin and Découvre Bitcoin
Status: Todo

**Comment by dadofsambonzuki** [comment]
It's showing now.

There was a bug not showing a communities with a `null` icon.

I've added a icon locally to the BTC Map web server for now.
