### ISSUE TITLE
Problem with "Nantes" geojson

### ISSUE THREAD

**Issue by Thomaasss** [teambtcmap/btcmap-data#3267]
We made a mistake on Nantes location. Below the right geojson
{"type":"Polygon","coordinates":[[[-1.9393397,47.1811281],[-1.8110566,47.1332576],[-1.8771224,47.0516668],[-1.8192457,47.0444745],[-1.8350734,47.011137],[-1.9171121,46.9747927],[-1.7457411,46.928353],[-1.7226371,46.8836794],[-1.5016413,46.8810886],[-1.5554194,47.0147835],[-1.4994697,47.0407123],[-1.4584043,46.9259847],[-1.3647498,46.9571297],[-1.3785742,47.0316797],[-1.3004487,47.0342876],[-1.2703629,47.0849538],[-1.201274,47.0402186],[-1.1159425,47.0414245],[-1.1700261,47.0935699],[-1.2495736,47.0984824],[-1.1617663,47.1778152],[-1.1814065,47.2408717],[-1.2545083,47.2480686],[-1.2962945,47.306138],[-1.390169,47.3085567],[-1.4034702,47.3440979],[-1.5314857,47.3100302],[-1.5741708,47.3532684],[-1.5846263,47.2726929],[-1.6430164,47.3096992],[-1.7184802,47.2777894],[-1.8207111,47.3317332],[-1.9197277,47.2846744],[-1.8628058,47.2346753],[-1.9393397,47.1811281]]]}

**Comment by dadofsambonzuki** [comment]
Updated.

Pls ensure the source data with Decouvre is updated too.
