### ISSUE TITLE
Australian Community

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#328]
/australia

-44.74662,105.54230,-8.34158,156.17400

**Comment by bubelov** [comment]
We have it for a long time. It's a country though, not a community.

https://api.btcmap.org/areas/au

**Comment by bubelov** [comment]
@dadofsambonzuki all areas are accessible by both ISO codes and full names, /au returns the same result as /australia

**Comment by dadofsambonzuki** [comment]
Awesome!
