### ISSUE TITLE
New GeoJSON region and logo for Bitcoin Ubuntu

### ISSUE THREAD

**Issue by BitcoinUbuntu** [teambtcmap/btcmap-data#3294]
As per title. 
I'm unsure how to add 'population' and 'population:date'. The population should be ~17500.

[bitcoin-ubuntu.zip](https://github.com/teambtcmap/btcmap-data/files/11184215/bitcoin-ubuntu.zi
![bitcoin-ubuntu-logo](https://user-images.githubusercontent.com/123870051/230764941-cc3ca4e8-99ff-4997-acc5-b1d220eba7bc.png)
p)

**Comment by dadofsambonzuki** [comment]
Done.

**Comment by BitcoinUbuntu** [comment]
Thank you very much! I can see the new region reflecting, please could we also update our profile picture to the official logo attached?

![230764941-cc3ca4e8-99ff-4997-acc5-b1d220eba7bc](https://user-images.githubusercontent.com/123870051/232079002-1dc1368f-fbdc-4b2d-8166-d5e664109a23.png)

**Comment by dadofsambonzuki** [comment]
Dome.
