### ISSUE TITLE
Pouch Bitcoin Island

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#33]
Local team have the [KML script HTML](https://data.btcmap.org/elements-pouch-island.html) and are working through it.

All links open an OSM editor centred on the location. Use the button zoom to pinpoint. Edit an existing location if present, create a new one if not.

https://btcmap.org/community/bitcoin-island-philippines

**Comment by bubelov** [comment]
Are we done with this list? I think we can close this issue

**Comment by dadofsambonzuki** [comment]
Yep, all done.
