### ISSUE TITLE
Bitcoin Ekasi

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#35]
Local team have the [KML import HTML](https://data.btcmap.org/elements-ekasi.html) to make location creation easier.

All links open an OSM editor centred on the location. Use the button zoom to pinpoint. Edit an existing location if present, create a new one if not.

https://btcmap.org/bitcoin-ekasi

**Comment by dadofsambonzuki** [comment]
Local team now working on tagging.

**Comment by bubelov** [comment]
Are they done?

**Comment by dadofsambonzuki** [comment]
9 of 19 done so far.

Gave some additional guidance to the Ekasi team today.

**Comment by dadofsambonzuki** [comment]
Still only 9 of 19 done. I will chase them again.

**Comment by dadofsambonzuki** [comment]
The 9 remaining are targets, not yet OP-ed.

This is now complete.
