### ISSUE TITLE
2140 Communities

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#3572]
Issue to get the 2140 communities into the DB.

Here is the [2140 Endpoint](https://2140meetups.com/wp-json/btcmap/v1/communities).

**Comment by danielcharrua** [comment]
- [ ] Escape characters for`/` needs to be removed.
`https:\/\/2140meetups.com\/wp-content\/uploads\/2022\/12\/bbo.jpg` should be `https://2140meetups.com/wp-content/uploads/2022/12/bbo.jpg`.
- [ ] `continent` tags need populating.
- [x] `population_date` needs to be either an integer or `null`, not `na`.
- [x] `geojson` should be `geo_json`

**Comment by danielcharrua** [comment]
@dadofsambonzuki as we are currently working with WordPress we can't control the slashing on the REST API response. Is there any possibility for you to process this task on your side?

If using JS you can use [JSON.parse(json)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) and the result will be as expected.

This may be an easy fix for this issue. Let me know your thoughts.

We are currently working on the `continents` tag because the API we were using is on maintenance. @tipogi

**Comment by dadofsambonzuki** [comment]
> If using JS you can use [JSON.parse(json)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) and the result will be as expected.

@bubelov - can your import script handle this?

**Comment by bubelov** [comment]
Imported. No guarantees it will work though

**Comment by dadofsambonzuki** [comment]
Mostly OK, but we have dupes for Malaga and Pontevedra.

Here are the two pre-existing communities, which we can now delete:

https://btcmap.org/community/m%C3%A1laga-2140

https://btcmap.org/community/pontevedra-2140

**Comment by dadofsambonzuki** [comment]
Bump @danielcharrua

**Comment by secondl1ght** [comment]
We should really check for dupes **before** importing and also think about some kind of validation script/process to automate these checks for efficiency and good test coverage.

Also if a non-required tag is `null` it can also be excluded entirely instead of included with a `null` value.

**Comment by dadofsambonzuki** [comment]
@bubelov - please can you run an update on the DB to set `continent=europe` for all areas where `organization=2140-meetups`.

**Comment by dadofsambonzuki** [comment]
Vast majority are European, a few South American though.

I can change them manually once the bulk change is done.

**Comment by secondl1ght** [comment]
And we also need to remove these dupes:

> Mostly OK, but we have dupes for Malaga and Pontevedra.
> 
> Here are the two pre-existing communities:
> 
> `málaga-2140` - https://btcmap.org/community/m%C3%A1laga-2140
> 
> `pontevedra-2140` - https://btcmap.org/community/pontevedra-2140
> 
> The new dupes are `pontevedra-_2140_` and `málaga-2140`
> 
> @danielcharrua - which ones do you want to keep?

**Comment by dadofsambonzuki** [comment]
> @bubelov - please can you run an update on the DB to set `continent=europe` for all areas where `organization=2140-meetups`.

I tried to run the following:

```
UPDATE area
SET tags = json_set(tags, '$.continent', 'europe')
WHERE json_extract(tags, '$.organization') = '2140-meetups';
```

But I'm hitting this error:

```
UNIQUE constraint failed: area.updated_at (19)
```

I tried adding in:

```
updated_at = datetime('now')
```

but no dice.

**Comment by dadofsambonzuki** [comment]
You should also take a look at the contact:telegram links. Some link to other social platforms.

**Comment by dadofsambonzuki** [comment]
Also see #3870 for changes to the Barca data that need to be made at your end.

I've made the changes locally for now, but they will be overwritten during the next import.

**Comment by danielcharrua** [comment]
@dadofsambonzuki we need to change the `contact:email` in all communities, actually we are sending the username and not the actual community email...

We are telling all communities to add the new email value, so all communities now will have an empty value. It is better for you have an empty value on the json or `null`?

**Comment by secondl1ght** [comment]
I will add the requirements to our Wiki so that any community orgs know what the standards are for these imports and we can reference this going forward.

**Comment by dadofsambonzuki** [comment]
We ideally need a JSON schema.

**Comment by secondl1ght** [comment]
Ok you can check out our 'schema' here now: https://github.com/teambtcmap/btcmap-api/wiki/5.-Areas#communities :)

**Comment by bubelov** [comment]
It looks like those communities are already imported and they're listed in our community catalog. If you need any further changes, please submit them in separate issues focused on the fields which need to be changed
