### ISSUE TITLE
Updated Einundzwanzig Community Data

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#3573]
Here is the [Einundzwanzig endpoint](https://portal.einundzwanzig.space/api/btc-map-communities).

Covers #3023 and #3502.

Needs re-importing into the DB when ready.

The following changes need implementing in the source data first:

1. `contact:twitter` needs to be either a URL including a twitter handle, `null` or absent. There are many entries in the data that are simply `"contact:twitter":"https://twitter.com/"`.

**Comment by HolgerHatGarKeineNode** [comment]
We've updated our code to:

```php
'contact:twitter'  => $meetup->twitter_username ? 'https://twitter.com/'.$meetup->twitter_username : null,
```

Thank you very much for this important advice.

**Comment by dadofsambonzuki** [comment]
Awesome.

@bubelov - can you run this through your script again and perhaps set a cronjob to pull the latest from the end point frequently? Say nightly?

**Comment by bubelov** [comment]
Imported
