### ISSUE TITLE
Good Hope Shop

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#43]
Merchant name: Good Hope Shop 
Address: C Hani street 
Location URL: https://maps.app.goo.gl/dZG2nahL39kwqGzEA
Business type: 
Payment methods: onchain,lightning,nfc
Twitter handle: 
Notes: 
Status: Todo
Created at: 2022-09-20T19:48:57.463Z

**Comment by bubelov** [comment]
There is no shop on Google Maps

**Comment by dadofsambonzuki** [comment]
Covered under #35.
