### ISSUE TITLE
Super Selectos - El Salvador

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#4429]
The Super Selectos chain of supermarkets in El Salvador apparently accepts BTC.

Here is an [overpass query](https://overpass-turbo.eu/s/1wyY) of the 68 Super Selectos stores in OSM.

Awaiting further evidence so that we can verify.

**Comment by bubelov** [comment]
https://www.facebook.com/147724765250673/posts/4505190596170713/

> 💰 To make your payment with Bitcoin through Chivo Wallet, keep these recommendations in mind
-
Available in all Super Selects in the country. 🙌🏻 Find the box identified for this form of payment in #TuSuper preferred.
-
Also, remember that you can always pay with: Cash, debit or credit cards, points and Gift Card. 💵💳
Restrictions apply. Does not apply to superselectos.com or the Super Selectos App

**Comment by bubelov** [comment]
This video is 2 months old, I think we have enough evidence

https://www.youtube.com/watch?v=vFwUzlb-TAQ

**Comment by bubelov** [comment]
First batch is submitted:

https://www.openstreetmap.org/changeset/139687086

Let's wait for a few day and see if local mappers have any feedback. This dataset is pretty small and the change is trivial so it shouldn't be a problem.

**Comment by bubelov** [comment]
The rest of the elements have been updated:

https://www.openstreetmap.org/changeset/139852203
