### ISSUE TITLE
Update Prague community

### ISSUE THREAD

**Issue by hynek-jina** [teambtcmap/btcmap-data#4768]
Please update https://btcmap.org/community/dvacet-jedna-praha
- change name from `Dvacet Jedna Praha` to `Jednadvacet Praha`
- update logo to:
![Black-vertical-logo](https://github.com/teambtcmap/btcmap-data/assets/26002916/3d19f45e-a70c-444a-89e0-9ea658c1dd2b)
- add website: https://jednadvacet.org/

Thank you!

**Comment by dadofsambonzuki** [comment]
We can change everything apart from the URL slug as that is the UID.

We can delete this community and create a new one. All you lose is the report history, although we could probably port that at some point (although it's not really important imo).

OK?

**Comment by hynek-jina** [comment]
I think that it is ok to remove history.. so feel free to refresh the link

**Comment by bubelov** [comment]
I deleted the old area, the new one is here:

https://api.btcmap.org/areas/jednadvacet-praha

**Comment by hynek-jina** [comment]
But the community is not created, right? Or can you please share the community link?

**Comment by dadofsambonzuki** [comment]
Web App needs upto 24hrs for the community to display as it has a
dependency on report generation, which is a daily batch.

**Comment by bubelov** [comment]
Here is a community link:

https://btcmap.org/community/jednadvacet-praha

Yea, there is a delay in the web app

**Comment by hynek-jina** [comment]
Nice.. thank you
