### ISSUE TITLE
Victoria Kayak Tours & Rentals

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#58]
Merchant name: Victoria Kayak Tours & Rentals
Address: 1006 Wharf Street, Victoria, B.C. V8W 1T4
Location URL: https://victoriakayak.com/
Business type: 
Payment methods: onchain,lightning
Twitter handle: @VictoriaKayak
Notes: Located on the Miners Landing Pier right next to Red Fish Blue Fish in downtown Victoria.
Status: Todo
Created at: 2022-09-22T01:47:52.027Z

**Comment by bubelov** [comment]
> Edited 24 days ago by [Liongrass](https://www.openstreetmap.org/user/Liongrass)

Someone already added this place: https://www.openstreetmap.org/node/2774325367
