### ISSUE TITLE
Various UK Merchants

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#61]
From the Bridge2Bitcoin map, here is the [KML parsed HTML](https://data.btcmap.org/elements-uk.html) for easier entry.

All links open an OSM editor centred on the location. Use the button zoom to pinpoint. Edit an existing location if present, create a new one if not.

**Comment by BitcoinMSW** [comment]
Updated with the following points to note:

Tredragon Pizza - added to map but note Google maps(!) says it is temporarily closed - is it a seasonal business?
Monusk Tapas and Wine - not added to map yet - Google maps(!) says it is permanently closed - is it?
RJ's; Real Bedford - Lightning_contactless=yes, but bitcoinevents suggests lightning_contactless=no - which is correct?
Eatme - not added as mobile/occasional
Aaron Dorn Hair - not added as couldn't see a building
J Ingram Developments - not added as couldn't see a building
Citadel Timber - not added as not a live merchant
Bitcoin Black Cab - not added as mobile
True Bites; White Wolf; Go Tennis; Kalvin the Cat Scratcher - not added as bitcoinevents suggests online only

Will ask bitcoinevents for clarification on the above

**Comment by dadofsambonzuki** [comment]
Excellent work, ser.

It's different here as they are all on one ticket, but for single Issue entries you can apply the Services label as we will have a service directory in the future for merchants without a physical presence.

**Comment by dadofsambonzuki** [comment]
Aaron Hair added under #265 via noob form submission.

RJ's and Real Bedford both accept contactless.

**Comment by dadofsambonzuki** [comment]
Are these all done now @BitcoinMSW?

If so we can close.

**Comment by BitcoinMSW** [comment]
Still a lot of very dubious ones remaining. Leave it open for now - I'll embark on a secondary purge and see if the UK meetup leaders can help flag out of date info

**Comment by dadofsambonzuki** [comment]
This Issue is more specifically about the Bridge2Bitcoin KML data import.

**Comment by dadofsambonzuki** [comment]
All the 80 locations in the KML list have been added? If so I think we can close this.

Verifying old data is a bigger issue. We'll probably end up creating country specific 'out-of-date' lists.

**Comment by BitcoinMSW** [comment]
Yeah, happy to close now :)
