### ISSUE TITLE
Bitcoin Jungle Merchants

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#6133]
Here is a current list of merchants in the [Bitcoin Jungle community](https://btcmap.org/community/bitcoin-jungle) specifically using the Bitcoin Jungle wallet:

https://maps.bitcoinjungle.app/api/list

We should take a look and cross reference with what we have, adding where necessary.

We are working with blink and Bitcoin Jungle on a way to sync data.

**Comment by stackingsaunter** [comment]
I finished adding all Jungle merchants to the map, excluding duplicates, closed businesses, online/non-physical services.

https://x.com/StackingSaunter/status/1870987681821524204
