### ISSUE TITLE
Snuups GmbH

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#62]
Merchant name: 
Address: Höhenweg 304 4716 Welschenrohr Switzerland
Location URL: [https://www.google.ch/maps/place/Höhenweg+304,+4716+Welschenrohr/@47.2818496,7.5255598,18.75z/data=!4m5!3m4!1s0x4791da20cd08640d:0xd948e8f06d0460a7!8m2!3d47.2824077!4d7.524461?hl=de](https://www.google.ch/maps/place/H%C3%B6henweg+304,+4716+Welschenrohr/@47.2818496,7.5255598,18.75z/data=!4m5!3m4!1s0x4791da20cd08640d:0xd948e8f06d0460a7!8m2!3d47.2824077!4d7.524461?hl=de)
Payment methods: onchain,lightning
Twitter merchant: 
Twitter submitter: 
Notes: Onlineshop for 3D Printing
Status: Todo
Created at: 2022-09-22T14:00:16.454Z

**Comment by trafficpest** [comment]
new to this what is the best pratice when they dont put a name?

**Comment by dadofsambonzuki** [comment]
Hmm. looks like I missed it in the initial data copy.

This is online only and so not suitable for the map.  Adding service label and closing.
