### ISSUE TITLE
Villa Leonor Beach Club

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#63]
Merchant name: Villa Leonor Beach Club
Address: https://www.google.com/maps/@9.113005,-83.694146,20z
Location URL: https://www.google.com/maps/@9.113005,-83.694146,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:23:44.503Z

**Comment by jmann6** [comment]
Done
https://www.openstreetmap.org/way/771975824
