### ISSUE TITLE
Laev

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#64]
Merchant name: Laev 
Address: https://www.google.com/maps/@10.083104893395,-84.473915335298,20z
Location URL: https://www.google.com/maps/@10.083104893395,-84.473915335298,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:14.534Z

**Comment by bubelov** [comment]
There is nothing here
