### ISSUE TITLE
Colina's Wood Fired Steaks And Pizza

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#65]
Merchant name: Colina's Wood Fired Steaks And Pizza
Address: https://www.google.com/maps/@9.4132921071933,-84.156108517271,20z
Location URL: https://www.google.com/maps/@9.4132921071933,-84.156108517271,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:14.076Z

**Comment by bubelov** [comment]
https://www.openstreetmap.org/changeset/126903180
