### ISSUE TITLE
Bitcoin ATM Edificio Trifami Bldg

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#66]
Merchant name: Bitcoin ATM Edificio Trifami Bldg. Suite 509  (behind Banco Central de Costa Rica)
Address: https://www.google.com/maps/@9.9348649727072,-84.079704165412,20z
Location URL: https://www.google.com/maps/@9.9348649727072,-84.079704165412,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:13.437Z

**Comment by bubelov** [comment]
https://www.openstreetmap.org/changeset/126903381
