### ISSUE TITLE
Hotel La Colina Manuel Antonio

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#68]
Merchant name: Hotel La Colina Manuel Antonio
Address: https://www.google.com/maps/@9.4133688295687,-84.156105754435,20z
Location URL: https://www.google.com/maps/@9.4133688295687,-84.156105754435,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:12.544Z

**Comment by bubelov** [comment]
https://www.openstreetmap.org/changeset/126943666
