### ISSUE TITLE
Frutas del Caribe

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#69]
Merchant name: Frutas del Caribe
Address: https://www.google.com/maps/@9.6574622699695,-82.755004654603,20z
Location URL: https://www.google.com/maps/@9.6574622699695,-82.755004654603,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:12.116Z

**Comment by BitcoinMSW** [comment]
https://www.openstreetmap.org/edit#map=19/9.65769/-82.79797

Point added with basic info and bitcoin tags
