### ISSUE TITLE
Club Gamer C.R

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#70]
Merchant name: Club Gamer C.R
Address: https://www.google.com/maps/@9.9916445418039,-83.03190468778,20z
Location URL: https://www.google.com/maps/@9.9916445418039,-83.03190468778,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:11.668Z

**Comment by bubelov** [comment]
Nothing on Google Maps
