### ISSUE TITLE
YAXA

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#71]
Merchant name: YAXA
Address: https://www.google.com/maps/@9.9457172389099,-85.66792680836,20z
Location URL: https://www.google.com/maps/@9.9457172389099,-85.66792680836,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:10.681Z

**Comment by bubelov** [comment]
https://www.openstreetmap.org/changeset/128091115
