### ISSUE TITLE
Bitcoin ATM By Edenia

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#72]
Merchant name: Bitcoin ATM By Edenia
Address: https://www.google.com/maps/@9.9349,-84.07963,20z
Location URL: https://www.google.com/maps/@9.9349,-84.07963,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:11.256Z

**Comment by jakubszwedo** [comment]
Not sure where exactly it is
Seems to be this one, but hard to locate https://www.google.com/search?tbs=lf:1,lf_ui:3&tbm=lcl&sxsrf=ALiCzsYo8F3XMSzNK7s5v0VGIZ6W_XOIRg:1667133231462&q=bitcoin+atm+san+jose+costa+rica&rflfq=1&num=10&ved=2ahUKEwjxsbeg-4f7AhWGlosKHUHOBeEQtgN6BAgNEAE#rlfi=hd:;si:;mv:[[10.111378799999999,-84.0468583],[9.586442,-84.6608279]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!2m1!1e3!3sIAE,lf:1,lf_ui:3
