### ISSUE TITLE
Oxygen Jungle Villas

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#73]
Merchant name: Oxygen Jungle Villas
Address: https://www.google.com/maps/@9.191666,-83.727559,20z
Location URL: https://www.google.com/maps/@9.191666,-83.727559,20z
Payment methods: onchain,lightning,nfc
Twitter merchant: 
Twitter submitter: @BitcoinJungleCR
Notes: 
Status: Todo
Created at: 2022-09-22T15:39:09.742Z

**Comment by BitcoinMSW** [comment]
Added point with basic info and bitcoin tags

https://www.openstreetmap.org/edit#map=19/9.19182/-83.72795
