### ISSUE TITLE
skledarnatuursteen

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#74]
Merchant name: skledarnatuursteen
Address: 5145 NW waalwijk energieweg 1
Location URL: https://www.google.com/maps/place/Skledar+Natuursteen+bv,+Energieweg+1,+5145+NW+Waalwijk/@51.6941153,5.0650099,17z/data=!4m5!3m4!1s0x47c693d644bd1627:0x973f4f94dd7ddf3b!8m2!3d51.6941153!4d5.0650099
Payment methods: onchain,lightning
Twitter merchant: 
Twitter submitter: 
Notes: Website: skledarnatuursteen.nl
Instagram: @skledarnatuursteen
Telefoon: +31 416316620

**Comment by cryptoteun** [comment]
Added via OSM: https://www.openstreetmap.org/node/2892139786
