### ISSUE TITLE
Arnhem Bitcoin City

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#75]
Lots of locations in Arnhem!

[Arnhem Merchant Map](https://www.arnhembitcoinstad.nl/kaart).

[Arnhem Telegram Group](https://t.me/Bitcoinstad).

**Comment by dadofsambonzuki** [comment]
Have spoken to Gnoek  (a local organiser) to see if we can get a KML of their locations so that we can put it through our script and enable them to more easily enter the data into OSM.

**Comment by cryptoteun** [comment]
Currently entering all items by hand

**Comment by dadofsambonzuki** [comment]
If you can get a KML export of your current data we can put it through our
script that creates a list of OSM edit links. This greatly speeds up the
process!

Also, we'll add your GH username to the Supertaggers team so you can manage
issues.

**Comment by cryptoteun** [comment]
I wrote a simple script which create copy/paste like data. This includes an osm link which includes street, house number and city. That works for now, +/- 30% to move to OSM

**Comment by cryptoteun** [comment]
Data from [Arnhem Merchant Map](https://www.arnhembitcoinstad.nl/kaart) is now completely added. 
Issue closed.

**Comment by dadofsambonzuki** [comment]
🔥🔥🔥

**Comment by dadofsambonzuki** [comment]
Shall we add Arnhem as a Community?

**Comment by cryptoteun** [comment]
Probably a good idea, what needs to be done for that.

**Comment by dadofsambonzuki** [comment]
https://btcmap.org/communities/add

**Comment by dadofsambonzuki** [comment]
Also, embedding is an option for you now if you're interested:

https://github.com/teambtcmap/btcmap.org#embedding
