### ISSUE TITLE
How to know what payment methods does a store use?

### ISSUE THREAD

**Issue by crannofonix** [teambtcmap/btcmap-data#792]
![image](https://user-images.githubusercontent.com/92416370/197235751-387e933a-e53a-47b6-a270-7c3563c2fb95.png)
Hey, I would like to contribute to OpenStreetMap, but whenever I look at this list or any other list, I see the places' names, locations, but it doesn't show what payment methods they use.

**Comment by jakubszwedo** [comment]
If I don't see any proof online (twitter, their website etc) I contact the merchant through facebook or email.

**Comment by secondl1ght** [comment]
Yes the only required tag is `currency:XBT=yes` all the others are optional, check out the Wiki for more info: https://github.com/teambtcmap/btcmap-data/wiki/Tagging-Instructions

**Comment by secondl1ght** [comment]
@crannofonix did this answer your question?
