### ISSUE TITLE
update community Bitcoin Twente

### ISSUE THREAD

**Issue by rdamink** [teambtcmap/btcmap-data#7969]
please update general data. Thank you.

mailadres info@bitcointwente.nl
web bitcointwente.nl
update logo - find attached.

![bitcoin twente v4-01](https://github.com/user-attachments/assets/4ca77ff5-634e-4410-a4b3-10feb2a0e3b8)

**Comment by dadofsambonzuki** [comment]
Done.

Sorry for the delay!
