### ISSUE TITLE
RSS feed error

### ISSUE THREAD

**Issue by LighthouseFR** [teambtcmap/btcmap-data#8358]
Following the [RSS post on Nostr](https://primal.net/e/note1xunftgqeheea2fzszn7lgya5dahq2z9e7qgf8cydh8n7k9ek27mqesac3q), I included below URL as a RSS feed. Unfortunately, it returns with an error message (see screenshot).

![rss-error](https://github.com/user-attachments/assets/aa85f076-0d76-4123-9c87-9ea950e9a3fd)

Can you please provide me with the correct feed?

**Comment by bubelov** [comment]
Here is the correct URL:

https://api.btcmap.org/feeds/new-places/fr

This feature is still experimental and it was not supposed to be announced to a wide audience yet, we'll add feed subscription buttons to the community and county pages eventually, so there will be no need to construct those links by hand

**Comment by LighthouseFR** [comment]
Thank you.
It works like a charm!!
