### ISSUE TITLE
Discussion: how to deal with online-only Bitcoin payments?

### ISSUE THREAD

**Issue by Talkless** [teambtcmap/btcmap-data#873]
Hi,

First of all, as a regular OSM contributor, I really appreciate idea of using it as a open data storage.

Question arises how to deal with places, that are marked accepting Bitcoin, but in reality it's only their _website_ are accepting Bitcoin.

For example, Lithuanian web hosting provider CherryServers (https://www.openstreetmap.org/node/2584656841) does accept Bitcoin via their Web, but I really _really_ doubt you could go physically into their office and pay for hosting services using Bitcoin there.

Another example is electronics shop Promaksa: https://www.openstreetmap.org/node/3257023577

They do specify in their website that the Bitcoin is accepted, and _maybe_ they do that in physical shop they have (it's not just an "office", they do state having a physical shop in the city), though that should be asked via email or visiting.

Now, not sure if OSM has tagging rules to specify only if website accepts payment method X. Maybe if it's only physical location that accepts cards/cash/xbt should be marked on OSM maps?

Probably this question would be best to ask in OSM mailing list? Though we could start here...

**Comment by bubelov** [comment]
@Talkless I think it was already settled that "virtual places" should be purged. They are a maintenance burden and they bring no value to anyone.

Relevant quotes [from the Wiki](https://wiki.openstreetmap.org/wiki/Cryptocurrency):

> Based on the principles of the openstreetmap practices, we only tag locations that accept the cryptocurrency at the physical location itself.

> In some counties delivery companies have started accepting crypto for a large number of restaurants, but only when you order via them and online. Tagging those restaurants as accepting crypto is not good practice as this creates a false expectation. Openstreetmap values [Verifiability](https://wiki.openstreetmap.org/wiki/Verifiability) and not being able to pay at the location with cryptocurrencies fails that.

Hotels are in a grey zone, I'd say they are OK to tag if you really can get there and make a booking on the spot. Delivery company analogy doesn't seem to apply here since it's a direct payment with no middleman.

**Comment by Talkless** [comment]
Thanks @bubelov , I didn't knew that article, that settles the question (and I agree to the OSM Wiki).

**Comment by Talkless** [comment]
@bubelov Probably taxi company office should also not be marked as accepting it, even if you can call taxi cab and pay on it?

https://btcmap.org/map?lat=54.7348373&long=25.2342783

**Comment by bubelov** [comment]
@Talkless yea, if you aren't supposed to pay at that location, it shouldn't have a `currency:XBT` tag, as far as I understand
