### ISSUE TITLE
New Wealth CoLab

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#88]
Merchant name: New Wealth CoLab
Address: 4007 N Taliaferro Ave
Location URL: https://maps.app.goo.gl/cBBumYjjNunkjDgn8?g_st=ic
Payment methods: onchain,lightning,nfc
Twitter merchant: @newwealthcolab
Twitter submitter: @realbmiddleton
Notes: Free Kratom or Kava seltzer on your first visit when you mention “BTC Map”
Status: Todo
Created at: 2022-09-22T22:09:20.858Z

**Comment by BigBossRabbit** [comment]
This has been uploaded.
