### ISSUE TITLE
Disconnect Art Gallery and Record Shop

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#89]
Merchant name: Disconnect Art Gallery and Record Shop
Address: Finowstrasse 25, 10247 Berlin
Lat: 
Long: 
OSM: 
Location URL: 
Payment methods: onchain,lightning
Twitter merchant: 
Twitter submitter: 
Notes: Art and music from other worlds
Status: Todo
Created at: 2022-09-23T06:12:07.117Z

**Comment by jungusemlevve** [comment]
https://www.openstreetmap.org/edit#map=20/52.51098/13.46714
