### ISSUE TITLE
Upgrade legacy tags

### ISSUE THREAD

**Issue by secondl1ght** [teambtcmap/btcmap-data#931]
Here is a list of the legacy nodes with the `payment:bitcoin` tag: https://data.btcmap.org/legacy-nodes.html

These need to be updated to the correct `currency:XBT` tag.

We're suggesting two options, both of them are fine at the moment:

1. Visit the place physically in order to confirm that the place is up-to-date. If you can't do that, you can contact the place using OSM contact tags or by finding the contact details somewhere else. Once you get the new data, you can replace the legacy `payment:bitcoin` tag with `currency:XBT` tag, containing a simple `yes` or `no` value. 
2. Just remove the old `payment:bitcoin` tag and replace it with `currency:XBT` tag, keeping the original value. It's also fine since it improves the data set, but the first approach adds even more value.

**Comment by jungusemlevve** [comment]
https://www.openstreetmap.org/edit?node=2556907436#map=20/47.03961/15.73356

**Comment by secondl1ght** [comment]
hey @jungusemlevve there are 1000s of legacy nodes that need updating - we will leave this issue open until they are all complete.

**Comment by jungusemlevve** [comment]
https://www.openstreetmap.org/edit?node=2556615434#map=20/-37.80118/144.95071

**Comment by jakubszwedo** [comment]
Do I need to update here which one I updated/deleted? Or just don't care and you can update/generate new list?


https://www.openstreetmap.org/edit?node=2627770514#map=20/39.95341/-75.17175|
https://www.openstreetmap.org/edit?node=3087161300#map=20/28.65720/-17.91496
https://www.openstreetmap.org/edit?node=2778151133#map=21/40.23866/-111.65879
https://www.openstreetmap.org/edit?node=10049617008#map=20/54.15187/-4.47858
https://www.openstreetmap.org/edit?node=10056613332#map=20/60.21074/25.05360

**Comment by dadofsambonzuki** [comment]
There are so many on here so no need to provide updates. The Legacy Node
list will not show the updated node.

We need to think about how to split them geographically and best split the
work.

**Comment by bubelov** [comment]
Just FYI: it's OK to upgrade tags without verifying that the merchants still accept bitcoins. The only thing which is necessary is to verify that those places still exist (prob with Google Maps and by visiting their website) and remove the closed ones. Adding a few contact tags won't hurt, too. This way, we won't be blocked during the first pass and we will be able to leverage our users so they can contact the merchants and report/verify them right from our apps.

**Comment by JG-SSYT** [comment]
https://www.openstreetmap.org/edit?node=2441495282#map=20/1.28215/103.85078
