### ISSUE TITLE
Price Auto Sales Uvita

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#95]
Merchant name: Price Auto Sales Uvita
Address: https://goo.gl/maps/hZRM4QdBcMtaVvfN9
Lat: 9.175048356130436
Long: -83.7436954525357
OSM: https://www.openstreetmap.org/#map=19/9.175048356130436/-83.7436954525357
Location URL: https://goo.gl/maps/hZRM4QdBcMtaVvfN9
Payment methods: onchain
Twitter merchant: 
Twitter submitter: 
Notes: https://priceautoscr.com/
Status: Todo
Created at: 2022-09-23T13:59:56.905Z

**Comment by BitcoinMSW** [comment]
https://www.openstreetmap.org/edit#map=19/9.17505/-83.74370

Added point with basic info and bitcoin tags
