### ISSUE TITLE
Pick n Pay

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#954]
https://www.cryptoconvert.co.za/pnp/

**Comment by jakubszwedo** [comment]
this makes my heart smile

**Comment by jakubszwedo** [comment]
all Cape Town done

**Comment by dadofsambonzuki** [comment]
> Do this accept contactless?

Nope. QR only and they're not native BOLT11 invoices. More like LNURL as they are constrained by the QR format supported by the POS.

**Comment by dadofsambonzuki** [comment]
We should probably tag these with `payment:cryptoqr=yes` as there is an additional app and step required to convert the POS QR code into a BOLT11 invoice QR that can then be used with your Bitcoin Lightning wallet.

@bubelov - Any opinions here?

**Comment by dadofsambonzuki** [comment]
Lets leave as is for now.

**Comment by jakubszwedo** [comment]
I think BSN21M might have finished all spots, but I am not sure

**Comment by jakubszwedo** [comment]
all seems to be done
