### ISSUE TITLE
Price Auto Sales Parrita

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#96]
Merchant name: Price Auto Sales Parrita
Address: https://goo.gl/maps/V2JmZmSk7rFqgYEN7
Lat: 9.530064
Long: -84.361798
OSM: https://www.openstreetmap.org/#map=19/9.530064/-84.361798
Location URL: https://goo.gl/maps/V2JmZmSk7rFqgYEN7
Payment methods: onchain
Twitter merchant: 
Twitter submitter: 
Notes: http://www.priceautoscr.com/
Status: Todo
Created at: 2022-09-23T14:01:27.741Z

**Comment by BitcoinMSW** [comment]
https://www.openstreetmap.org/edit#map=19/9.53006/-84.36180

Added point with bitcoin tags and basic info
