### ISSUE TITLE
Welcome School

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#97]
Merchant name: Welcome School
Address: Via Antonio Gallus, 18, Selargius, Metropolitan City of Cagliari, Italy
Lat: 
Long: 
OSM: 
Location URL: https://www.google.com/maps/place/39%C2%B015%2711.6%22N+9%C2%B010%2716.6%22E/@39.2532172,9.1712773,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x4c7656a3ee71c79f!8m2!3d39.2532172!4d9.1712773
Payment methods: onchain
Twitter merchant: 
Twitter submitter: 
Notes: www.welcomeschool.it
Status: Todo
Created at: 2022-09-23T15:06:57.304Z

**Comment by BitcoinMSW** [comment]
https://www.openstreetmap.org/edit#map=20/39.25321/9.17150

Added bitcoin tags and website
