### ISSUE TITLE
a&o kreston ag

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#98]
Merchant name: a&o kreston ag
Address: Husmatt 1, 5400 Baden
Lat: 
Long: 
OSM: 
Location URL: https://www.kreston.ch/
Payment methods: onchain,lightning
Twitter merchant: 
Twitter submitter: 
Notes: 
Status: Todo
Created at: 2022-09-23T16:11:15.899Z

**Comment by jungusemlevve** [comment]
https://www.openstreetmap.org/edit#map=20/47.19202/8.51223
