### ISSUE TITLE
Casanova Bar & Restaurant

### ISSUE THREAD

**Issue by dadofsambonzuki** [teambtcmap/btcmap-data#99]
Merchant name: Casanova Bar & Restaurant
Address: Stadtturmstrasse 20, 5400 Baden
Lat: 
Long: 
OSM: 
Location URL: https://www.casanovabaden.ch/
Payment methods: onchain,lightning
Twitter merchant: 
Twitter submitter: 
Notes: 
Status: Todo
Created at: 2022-09-23T16:10:26.286Z

**Comment by bubelov** [comment]
https://www.openstreetmap.org/node/1598827664
